circledata:
	python plot_from_file.py -f sd_pressure_circledata.csv -s 2000 -e 2500 -c 0,1,2
signdata:
	python plot_from_file.py -f sd_pressure_signdata.csv -s 660 -e 1100 -c 0,1,3
ble:
	python plot_from_file.py -f ble_accelerometer_data_circle_Sensortile.csv -c 0,1,2
